use master
go
create database QLNCKH_SV
go
use QLNCKH_SV
go

CREATE TABLE KHOA(
	MAKHOA CHAR(10) NOT NULL,
	TENKHOA NVARCHAR(50) NOT NULL UNIQUE,
	NAMTHANHLAP INT,
	CONSTRAINT PK_KHOA PRIMARY KEY(MAKHOA)
)
CREATE TABLE GIANGVIEN(
	MAGV CHAR(10) NOT NULL,
	HOLOT NVARCHAR(50) NOT NULL ,
	TENGV NVARCHAR(15) NOT NULL,
	GIOITINH NVARCHAR(3) NOT NULL,
	TRINHDO NVARCHAR(30) NOT NULL,
	MAKHOA CHAR(10),
	CONSTRAINT FK_GV_KHOA FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA),
	CONSTRAINT PK_GV PRIMARY KEY (MAGV)
)
CREATE TABLE SINHVIEN(
	MASV CHAR(13) NOT NULL,
	HOLOT NVARCHAR(50) NOT NULL ,
	TENSV NVARCHAR(15) NOT NULL,
	GIOITINH NVARCHAR(3) NOT NULL,
	MAKHOA CHAR(10),
	CONSTRAINT FK_SV_KHOA FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA),
	CONSTRAINT PK_SV PRIMARY KEY (MASV)
)
CREATE TABLE DETAI(
	MADT CHAR(10) NOT NULL,
	TENDT NVARCHAR(50) NOT NULL,
	KINHPHI DECIMAL(10,0),
	NGAYBD DATETIME,
	NGAYKT DATETIME,
	MAGVHD CHAR(10) NOT NULL,
	MASV_CNDT CHAR(13) NOT NULL,
	CONSTRAINT FK_DT_GV FOREIGN KEY(MAGVHD) REFERENCES GIANGVIEN(MAGV),
	CONSTRAINT FK_DT_SV FOREIGN KEY(MASV_CNDT) REFERENCES SINHVIEN(MASV),
	CONSTRAINT PK_DT PRIMARY KEY (MADT)
)
CREATE TABLE THAMGIADETAI
(
	MADT CHAR(10), 
	MASV CHAR(13),
	PHUCAP NUMERIC(10,0),
	KETQUA NVARCHAR(30),
	CONSTRAINT PK_TGDT PRIMARY KEY (MADT, MASV),
	CONSTRAINT FK_TGDT_DT FOREIGN KEY(MADT) REFERENCES DETAI(MADT),
	CONSTRAINT FK_TGDT_SV FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV),
)